// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmTMJq0o89-Jwk9PAGYxtJvx5gHwvDa20',
    appId: '1:859516422587:web:643656cbdd1af6810e9c9e',
    messagingSenderId: '859516422587',
    projectId: 'todo-app-31c34',
    authDomain: 'todo-app-31c34.firebaseapp.com',
    storageBucket: 'todo-app-31c34.firebasestorage.app',
    measurementId: 'G-6MBSMPGVK8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPm_5TDQqIP-4ZcAuHysk-odUDjWOYOkA',
    appId: '1:859516422587:android:b4c91166b6c9f8420e9c9e',
    messagingSenderId: '859516422587',
    projectId: 'todo-app-31c34',
    storageBucket: 'todo-app-31c34.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCqFBILns5z3A82eYRC9GeRTHhO0jEWIg',
    appId: '1:859516422587:ios:cec131b46cfcca160e9c9e',
    messagingSenderId: '859516422587',
    projectId: 'todo-app-31c34',
    storageBucket: 'todo-app-31c34.firebasestorage.app',
    iosBundleId: 'com.example.todo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBCqFBILns5z3A82eYRC9GeRTHhO0jEWIg',
    appId: '1:859516422587:ios:cec131b46cfcca160e9c9e',
    messagingSenderId: '859516422587',
    projectId: 'todo-app-31c34',
    storageBucket: 'todo-app-31c34.firebasestorage.app',
    iosBundleId: 'com.example.todo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAmTMJq0o89-Jwk9PAGYxtJvx5gHwvDa20',
    appId: '1:859516422587:web:04f438b1fb7b647a0e9c9e',
    messagingSenderId: '859516422587',
    projectId: 'todo-app-31c34',
    authDomain: 'todo-app-31c34.firebaseapp.com',
    storageBucket: 'todo-app-31c34.firebasestorage.app',
    measurementId: 'G-B8NRWZJDMN',
  );
}
